version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Deploy AWS infrastructure"
          command: |
            aws cloudformation deploy \
            --stack-name prod-${CIRCLE_WORKFLOW_ID} \
            --template-file template.yml
      - run: return 1
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail

  configure_infrastructure:
    docker:
        - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "e2:c9:22:04:6c:5c:91:d9:6b:fa:69:21:5b:be:a7:ad"
      - run:
          name: "Install dependencies"
          command: |
            apk add --update ansible
      - run:
          name: "Configure server"
          command: |
            ansible-playbook -i inventory main.yml
  
  smoke_test:
    docker: 
      - image: alpine:latest
    steps: 
      - run:
            name: "Install curl"
            command: |
              apk --no-cache add curl
      - run: 
          name: "Verify website is responding"
          command: |
            URL="https://google.com"
            if curl -s --head ${URL}
            then
              echo "It worked!"
              return 0
            else
              echo "It failed"
              return 1
            fi
  
workflows:
  playground:
    jobs:
      - create_infrastructure
      # - configure_infrastructure
      # - smoke_test