---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install packages"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - npm
    - nodejs

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create directory"
  file:
    path: ~/web
    state: directory

- name: "Copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Executing node"
  shell: |
    pm2 start ~/web/index.js -f